### ISSUE TITLE
How do I get data out of a parsed instrument?

### ISSUE THREAD

**Issue by stijnfrishert** [andamira/sofiza#1]
Hey, took a look at the library and this looks great! I'd love to use it for one of my projects, but how do I access the actual groups, regions, opcodes, etc. in an `Instrument`?

So far the only functions I see return a group or region _count_.

**Comment by joseluis** [comment]
@stijnfrishert thank you for the heads up! I totally forgot about that part ;)

I've just released version 0.2 now with public fields for Instrument, Group and Region structs.

Apart from that I'd like to make a nicer API with iterators at some point. But for now this should be enough.

**Comment by stijnfrishert** [comment]
Thanks for the quick reply :D Looks much better. Could I get access to the `default_path` as well, though? 😅

**Comment by joseluis** [comment]
you're right, let me publish a new version

**Comment by stijnfrishert** [comment]
Thanks, I just loaded my first couple of sfz's and played them :) Nice!

**Comment by joseluis** [comment]
I'm glad it works!

BTW feel free to collaborate with an example of use if you so desire

**Comment by stijnfrishert** [comment]
Thanks! I haven't published any of my code, but will let you know (and credit Sofiza) when I do :)
