### ISSUE TITLE
Group opcodes seem wrong

### ISSUE THREAD

**Issue by stijnfrishert** [andamira/sofiza#3]
I'm loading the following SFZ: https://www.karoryfer.com/karoryfer-samples/emilyguitar.

When iterating over `instrument.regions`, the first region is the one with sample `"release/d6_release_rr1.wav"`. Apparently its group id is `0`.

I then look up the opcodes in group 0, which look like this:

![image](https://user-images.githubusercontent.com/7056711/115159307-cd99a500-a092-11eb-9db1-033f26270b5a.png)

But when I look up the group opcodes in the .sfz that belong to that region, this is what is says:

```
<group>
lokey=85
hikey=89
trigger=release
pitch_keycenter=86
bend_up=1200
bend_down=-1200
volume=-6
amp_random=3
rt_decay=7
ampeg_release=0.300
```

Where does Sofiza get `lovel` and `hivel` from?

**Comment by stijnfrishert** [comment]
Looks like `bend_up` and `bend_down` got transformd into `lovel` and `hivel`. I don't think Sofiza currently supports them, which is fine, but I wouldn't expect it to _insert_ other opcodes in its place?

**Comment by joseluis** [comment]
I've fixed a couple parsing errors, and I've also added the bend_up & bend_down opcodes.

could you try it  with the latest 0.2.2 version to see if it's fixed?

**Comment by stijnfrishert** [comment]
Yes, it recognizes them as bend_up and bend_down now :)
